export const CART = {
  DISCOUNT: "Discount",
  PRICE: "PRICE",
  PROCEED_TO_CHECKOUT: "PROCEED TO CHECKOUT",
  PRODUCT: "PRODUCT",
  QUANTITY: "QUANTITY",
  RETURN_TO_SHOP: "RETURN TO SHOP",
  SHOPPING_CART: "Shooping Cart",
  SUB_TOTAL: "SUB-TOTAL",
  TOTAL: "Total",
  UPDATE_CART: "UPDATE CART",
};
